# Generated by Django 4.0.3 on 2024-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttb',
            name='grp_link',
            field=models.CharField(max_length=200),
        ),
    ]
