# Generated by Django 4.0.3 on 2024-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_studenttb_grp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttb',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttb',
            name='grp_link',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='GroupLinkTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('class_section', models.CharField(max_length=50)),
                ('grp_link', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('year', 'class_section')},
            },
        ),
    ]
